#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorySheet
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CrimenDatabase")]
	public partial class DBCrimeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Crime(Tbl_Crime instance);
    partial void UpdateTbl_Crime(Tbl_Crime instance);
    partial void DeleteTbl_Crime(Tbl_Crime instance);
    partial void InsertCrime_Criminal(Crime_Criminal instance);
    partial void UpdateCrime_Criminal(Crime_Criminal instance);
    partial void DeleteCrime_Criminal(Crime_Criminal instance);
    partial void InsertTbl_Criminal(Tbl_Criminal instance);
    partial void UpdateTbl_Criminal(Tbl_Criminal instance);
    partial void DeleteTbl_Criminal(Tbl_Criminal instance);
    partial void InsertTbl_Modus(Tbl_Modus instance);
    partial void UpdateTbl_Modus(Tbl_Modus instance);
    partial void DeleteTbl_Modus(Tbl_Modus instance);
    #endregion
		
		public DBCrimeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CrimenDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCrimeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCrimeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCrimeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCrimeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Crime> Tbl_Crimes
		{
			get
			{
				return this.GetTable<Tbl_Crime>();
			}
		}
		
		public System.Data.Linq.Table<Crime_Criminal> Crime_Criminals
		{
			get
			{
				return this.GetTable<Crime_Criminal>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Criminal> Tbl_Criminals
		{
			get
			{
				return this.GetTable<Tbl_Criminal>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Modus> Tbl_Modus
		{
			get
			{
				return this.GetTable<Tbl_Modus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Crime")]
	public partial class Tbl_Crime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CaseNo;
		
		private string _PS;
		
		private string _Place;
		
		private string _Place_Type;
		
		private System.Nullable<System.DateTime> _DateReporting;
		
		private System.Nullable<System.TimeSpan> _TimeReporting;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<System.TimeSpan> _Time;
		
		private string _Year;
		
		private string _Weapon_Equipment;
		
		private string _Mode_Transpassing;
		
		private string _Part_Day;
		
		private string _M_Z;
		
		private string _Special_Occasion;
		
		private string _Longitude;
		
		private string _Latitude;
		
		private string _Area;
		
		private string _Property_Stolen;
		
		private string _Complainant_Name;
		
		private string _Father_HusbandsName;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _MobileNo;
		
		private System.Nullable<int> _Age;
		
		private string _Sex;
		
		private string _Occupation;
		
		private string _Remarks;
		
		private System.Nullable<bool> _Property_Offence;
		
		private string _Property_Type;
		
		private string _Property_Value;
		
		private string _Property_Remakrs;
		
		private string _MO_Type;
		
		private string _MO_Remarks;
		
		private string _Sections;
		
		private string _IO;
		
		private string _Status;
		
		private string _Status_No;
		
		private string _Case_Remarks;
		
		private string _Picture_Place;
		
		private string _Picture_Place1;
		
		private string _Picture_Place2;
		
		private string _Picture_Place3;
		
		private string _Picture_Weapon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCaseNoChanging(System.Nullable<int> value);
    partial void OnCaseNoChanged();
    partial void OnPSChanging(string value);
    partial void OnPSChanged();
    partial void OnPlaceChanging(string value);
    partial void OnPlaceChanged();
    partial void OnPlace_TypeChanging(string value);
    partial void OnPlace_TypeChanged();
    partial void OnDateReportingChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReportingChanged();
    partial void OnTimeReportingChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTimeReportingChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTimeChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnWeapon_EquipmentChanging(string value);
    partial void OnWeapon_EquipmentChanged();
    partial void OnMode_TranspassingChanging(string value);
    partial void OnMode_TranspassingChanged();
    partial void OnPart_DayChanging(string value);
    partial void OnPart_DayChanged();
    partial void OnM_ZChanging(string value);
    partial void OnM_ZChanged();
    partial void OnSpecial_OccasionChanging(string value);
    partial void OnSpecial_OccasionChanged();
    partial void OnLongitudeChanging(string value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(string value);
    partial void OnLatitudeChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnProperty_StolenChanging(string value);
    partial void OnProperty_StolenChanged();
    partial void OnComplainant_NameChanging(string value);
    partial void OnComplainant_NameChanged();
    partial void OnFather_HusbandsNameChanging(string value);
    partial void OnFather_HusbandsNameChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnProperty_OffenceChanging(System.Nullable<bool> value);
    partial void OnProperty_OffenceChanged();
    partial void OnProperty_TypeChanging(string value);
    partial void OnProperty_TypeChanged();
    partial void OnProperty_ValueChanging(string value);
    partial void OnProperty_ValueChanged();
    partial void OnProperty_RemakrsChanging(string value);
    partial void OnProperty_RemakrsChanged();
    partial void OnMO_TypeChanging(string value);
    partial void OnMO_TypeChanged();
    partial void OnMO_RemarksChanging(string value);
    partial void OnMO_RemarksChanged();
    partial void OnSectionsChanging(string value);
    partial void OnSectionsChanged();
    partial void OnIOChanging(string value);
    partial void OnIOChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStatus_NoChanging(string value);
    partial void OnStatus_NoChanged();
    partial void OnCase_RemarksChanging(string value);
    partial void OnCase_RemarksChanged();
    partial void OnPicture_PlaceChanging(string value);
    partial void OnPicture_PlaceChanged();
    partial void OnPicture_Place1Changing(string value);
    partial void OnPicture_Place1Changed();
    partial void OnPicture_Place2Changing(string value);
    partial void OnPicture_Place2Changed();
    partial void OnPicture_Place3Changing(string value);
    partial void OnPicture_Place3Changed();
    partial void OnPicture_WeaponChanging(string value);
    partial void OnPicture_WeaponChanged();
    #endregion
		
		public Tbl_Crime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseNo", DbType="Int")]
		public System.Nullable<int> CaseNo
		{
			get
			{
				return this._CaseNo;
			}
			set
			{
				if ((this._CaseNo != value))
				{
					this.OnCaseNoChanging(value);
					this.SendPropertyChanging();
					this._CaseNo = value;
					this.SendPropertyChanged("CaseNo");
					this.OnCaseNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PS", DbType="VarChar(50)")]
		public string PS
		{
			get
			{
				return this._PS;
			}
			set
			{
				if ((this._PS != value))
				{
					this.OnPSChanging(value);
					this.SendPropertyChanging();
					this._PS = value;
					this.SendPropertyChanged("PS");
					this.OnPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place", DbType="VarChar(500)")]
		public string Place
		{
			get
			{
				return this._Place;
			}
			set
			{
				if ((this._Place != value))
				{
					this.OnPlaceChanging(value);
					this.SendPropertyChanging();
					this._Place = value;
					this.SendPropertyChanged("Place");
					this.OnPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place_Type", DbType="VarChar(50)")]
		public string Place_Type
		{
			get
			{
				return this._Place_Type;
			}
			set
			{
				if ((this._Place_Type != value))
				{
					this.OnPlace_TypeChanging(value);
					this.SendPropertyChanging();
					this._Place_Type = value;
					this.SendPropertyChanged("Place_Type");
					this.OnPlace_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReporting", DbType="Date")]
		public System.Nullable<System.DateTime> DateReporting
		{
			get
			{
				return this._DateReporting;
			}
			set
			{
				if ((this._DateReporting != value))
				{
					this.OnDateReportingChanging(value);
					this.SendPropertyChanging();
					this._DateReporting = value;
					this.SendPropertyChanged("DateReporting");
					this.OnDateReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeReporting", DbType="Time")]
		public System.Nullable<System.TimeSpan> TimeReporting
		{
			get
			{
				return this._TimeReporting;
			}
			set
			{
				if ((this._TimeReporting != value))
				{
					this.OnTimeReportingChanging(value);
					this.SendPropertyChanging();
					this._TimeReporting = value;
					this.SendPropertyChanged("TimeReporting");
					this.OnTimeReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="VarChar(4)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weapon_Equipment", DbType="VarChar(50)")]
		public string Weapon_Equipment
		{
			get
			{
				return this._Weapon_Equipment;
			}
			set
			{
				if ((this._Weapon_Equipment != value))
				{
					this.OnWeapon_EquipmentChanging(value);
					this.SendPropertyChanging();
					this._Weapon_Equipment = value;
					this.SendPropertyChanged("Weapon_Equipment");
					this.OnWeapon_EquipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode_Transpassing", DbType="VarChar(50)")]
		public string Mode_Transpassing
		{
			get
			{
				return this._Mode_Transpassing;
			}
			set
			{
				if ((this._Mode_Transpassing != value))
				{
					this.OnMode_TranspassingChanging(value);
					this.SendPropertyChanging();
					this._Mode_Transpassing = value;
					this.SendPropertyChanged("Mode_Transpassing");
					this.OnMode_TranspassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Part_Day", DbType="VarChar(50)")]
		public string Part_Day
		{
			get
			{
				return this._Part_Day;
			}
			set
			{
				if ((this._Part_Day != value))
				{
					this.OnPart_DayChanging(value);
					this.SendPropertyChanging();
					this._Part_Day = value;
					this.SendPropertyChanged("Part_Day");
					this.OnPart_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[M-Z]", Storage="_M_Z", DbType="VarChar(50)")]
		public string M_Z
		{
			get
			{
				return this._M_Z;
			}
			set
			{
				if ((this._M_Z != value))
				{
					this.OnM_ZChanging(value);
					this.SendPropertyChanging();
					this._M_Z = value;
					this.SendPropertyChanged("M_Z");
					this.OnM_ZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special_Occasion", DbType="VarChar(50)")]
		public string Special_Occasion
		{
			get
			{
				return this._Special_Occasion;
			}
			set
			{
				if ((this._Special_Occasion != value))
				{
					this.OnSpecial_OccasionChanging(value);
					this.SendPropertyChanging();
					this._Special_Occasion = value;
					this.SendPropertyChanged("Special_Occasion");
					this.OnSpecial_OccasionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="VarChar(50)")]
		public string Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="VarChar(50)")]
		public string Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Stolen", DbType="VarChar(100)")]
		public string Property_Stolen
		{
			get
			{
				return this._Property_Stolen;
			}
			set
			{
				if ((this._Property_Stolen != value))
				{
					this.OnProperty_StolenChanging(value);
					this.SendPropertyChanging();
					this._Property_Stolen = value;
					this.SendPropertyChanged("Property_Stolen");
					this.OnProperty_StolenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complainant_Name", DbType="VarChar(MAX)")]
		public string Complainant_Name
		{
			get
			{
				return this._Complainant_Name;
			}
			set
			{
				if ((this._Complainant_Name != value))
				{
					this.OnComplainant_NameChanging(value);
					this.SendPropertyChanging();
					this._Complainant_Name = value;
					this.SendPropertyChanged("Complainant_Name");
					this.OnComplainant_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Father/HusbandsName]", Storage="_Father_HusbandsName", DbType="VarChar(MAX)")]
		public string Father_HusbandsName
		{
			get
			{
				return this._Father_HusbandsName;
			}
			set
			{
				if ((this._Father_HusbandsName != value))
				{
					this.OnFather_HusbandsNameChanging(value);
					this.SendPropertyChanging();
					this._Father_HusbandsName = value;
					this.SendPropertyChanged("Father_HusbandsName");
					this.OnFather_HusbandsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(200)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(200)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(200)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(50)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(50)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="VarChar(100)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Offence", DbType="Bit")]
		public System.Nullable<bool> Property_Offence
		{
			get
			{
				return this._Property_Offence;
			}
			set
			{
				if ((this._Property_Offence != value))
				{
					this.OnProperty_OffenceChanging(value);
					this.SendPropertyChanging();
					this._Property_Offence = value;
					this.SendPropertyChanged("Property_Offence");
					this.OnProperty_OffenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Type", DbType="VarChar(100)")]
		public string Property_Type
		{
			get
			{
				return this._Property_Type;
			}
			set
			{
				if ((this._Property_Type != value))
				{
					this.OnProperty_TypeChanging(value);
					this.SendPropertyChanging();
					this._Property_Type = value;
					this.SendPropertyChanged("Property_Type");
					this.OnProperty_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Value", DbType="VarChar(100)")]
		public string Property_Value
		{
			get
			{
				return this._Property_Value;
			}
			set
			{
				if ((this._Property_Value != value))
				{
					this.OnProperty_ValueChanging(value);
					this.SendPropertyChanging();
					this._Property_Value = value;
					this.SendPropertyChanged("Property_Value");
					this.OnProperty_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Remakrs", DbType="VarChar(MAX)")]
		public string Property_Remakrs
		{
			get
			{
				return this._Property_Remakrs;
			}
			set
			{
				if ((this._Property_Remakrs != value))
				{
					this.OnProperty_RemakrsChanging(value);
					this.SendPropertyChanging();
					this._Property_Remakrs = value;
					this.SendPropertyChanged("Property_Remakrs");
					this.OnProperty_RemakrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_Type", DbType="VarChar(100)")]
		public string MO_Type
		{
			get
			{
				return this._MO_Type;
			}
			set
			{
				if ((this._MO_Type != value))
				{
					this.OnMO_TypeChanging(value);
					this.SendPropertyChanging();
					this._MO_Type = value;
					this.SendPropertyChanged("MO_Type");
					this.OnMO_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_Remarks", DbType="VarChar(600)")]
		public string MO_Remarks
		{
			get
			{
				return this._MO_Remarks;
			}
			set
			{
				if ((this._MO_Remarks != value))
				{
					this.OnMO_RemarksChanging(value);
					this.SendPropertyChanging();
					this._MO_Remarks = value;
					this.SendPropertyChanged("MO_Remarks");
					this.OnMO_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sections", DbType="VarChar(MAX)")]
		public string Sections
		{
			get
			{
				return this._Sections;
			}
			set
			{
				if ((this._Sections != value))
				{
					this.OnSectionsChanging(value);
					this.SendPropertyChanging();
					this._Sections = value;
					this.SendPropertyChanged("Sections");
					this.OnSectionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IO", DbType="VarChar(200)")]
		public string IO
		{
			get
			{
				return this._IO;
			}
			set
			{
				if ((this._IO != value))
				{
					this.OnIOChanging(value);
					this.SendPropertyChanging();
					this._IO = value;
					this.SendPropertyChanged("IO");
					this.OnIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_No", DbType="VarChar(100)")]
		public string Status_No
		{
			get
			{
				return this._Status_No;
			}
			set
			{
				if ((this._Status_No != value))
				{
					this.OnStatus_NoChanging(value);
					this.SendPropertyChanging();
					this._Status_No = value;
					this.SendPropertyChanged("Status_No");
					this.OnStatus_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Case_Remarks", DbType="VarChar(MAX)")]
		public string Case_Remarks
		{
			get
			{
				return this._Case_Remarks;
			}
			set
			{
				if ((this._Case_Remarks != value))
				{
					this.OnCase_RemarksChanging(value);
					this.SendPropertyChanging();
					this._Case_Remarks = value;
					this.SendPropertyChanged("Case_Remarks");
					this.OnCase_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Place", DbType="VarChar(MAX)")]
		public string Picture_Place
		{
			get
			{
				return this._Picture_Place;
			}
			set
			{
				if ((this._Picture_Place != value))
				{
					this.OnPicture_PlaceChanging(value);
					this.SendPropertyChanging();
					this._Picture_Place = value;
					this.SendPropertyChanged("Picture_Place");
					this.OnPicture_PlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Place1", DbType="VarChar(MAX)")]
		public string Picture_Place1
		{
			get
			{
				return this._Picture_Place1;
			}
			set
			{
				if ((this._Picture_Place1 != value))
				{
					this.OnPicture_Place1Changing(value);
					this.SendPropertyChanging();
					this._Picture_Place1 = value;
					this.SendPropertyChanged("Picture_Place1");
					this.OnPicture_Place1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Place2", DbType="VarChar(MAX)")]
		public string Picture_Place2
		{
			get
			{
				return this._Picture_Place2;
			}
			set
			{
				if ((this._Picture_Place2 != value))
				{
					this.OnPicture_Place2Changing(value);
					this.SendPropertyChanging();
					this._Picture_Place2 = value;
					this.SendPropertyChanged("Picture_Place2");
					this.OnPicture_Place2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Place3", DbType="VarChar(MAX)")]
		public string Picture_Place3
		{
			get
			{
				return this._Picture_Place3;
			}
			set
			{
				if ((this._Picture_Place3 != value))
				{
					this.OnPicture_Place3Changing(value);
					this.SendPropertyChanging();
					this._Picture_Place3 = value;
					this.SendPropertyChanged("Picture_Place3");
					this.OnPicture_Place3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Weapon", DbType="VarChar(MAX)")]
		public string Picture_Weapon
		{
			get
			{
				return this._Picture_Weapon;
			}
			set
			{
				if ((this._Picture_Weapon != value))
				{
					this.OnPicture_WeaponChanging(value);
					this.SendPropertyChanging();
					this._Picture_Weapon = value;
					this.SendPropertyChanged("Picture_Weapon");
					this.OnPicture_WeaponChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Crime_Criminal")]
	public partial class Crime_Criminal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JoinID;
		
		private int _Crime;
		
		private int _Criminal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJoinIDChanging(int value);
    partial void OnJoinIDChanged();
    partial void OnCrimeChanging(int value);
    partial void OnCrimeChanged();
    partial void OnCriminalChanging(int value);
    partial void OnCriminalChanged();
    #endregion
		
		public Crime_Criminal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int JoinID
		{
			get
			{
				return this._JoinID;
			}
			set
			{
				if ((this._JoinID != value))
				{
					this.OnJoinIDChanging(value);
					this.SendPropertyChanging();
					this._JoinID = value;
					this.SendPropertyChanged("JoinID");
					this.OnJoinIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Crime", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Crime
		{
			get
			{
				return this._Crime;
			}
			set
			{
				if ((this._Crime != value))
				{
					this.OnCrimeChanging(value);
					this.SendPropertyChanging();
					this._Crime = value;
					this.SendPropertyChanged("Crime");
					this.OnCrimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criminal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Criminal
		{
			get
			{
				return this._Criminal;
			}
			set
			{
				if ((this._Criminal != value))
				{
					this.OnCriminalChanging(value);
					this.SendPropertyChanging();
					this._Criminal = value;
					this.SendPropertyChanged("Criminal");
					this.OnCriminalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Criminal")]
	public partial class Tbl_Criminal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Short_Name;
		
		private string _Accused_FName;
		
		private string _Cast;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _YearofBirth;
		
		private string _Visiting_Place;
		
		private string _Occupation;
		
		private string _Bank_Account;
		
		private string _Habits;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Police_Station;
		
		private string _State;
		
		private string _PAddress1;
		
		private string _PAddress2;
		
		private string _PAddress3;
		
		private string _PPolice_Station;
		
		private string _PState;
		
		private string _Mobile;
		
		private string _Built;
		
		private string _Height;
		
		private string _Weight;
		
		private string _Skin_Color;
		
		private System.Nullable<int> _Age;
		
		private string _Logitude;
		
		private string _Latitude;
		
		private string _Picture_Front;
		
		private string _Picture_Side_Left;
		
		private string _Picture_Side_Right;
		
		private string _Picture_Uinq;
		
		private string _Other_Remarks;
		
		private string _Category;
		
		private string _Classification;
		
		private string _Status;
		
		private string _GangName;
		
		private string _Advocate;
		
		private string _Bailer;
		
		private string _RemarksAdv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShort_NameChanging(string value);
    partial void OnShort_NameChanged();
    partial void OnAccused_FNameChanging(string value);
    partial void OnAccused_FNameChanged();
    partial void OnCastChanging(string value);
    partial void OnCastChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnYearofBirthChanging(string value);
    partial void OnYearofBirthChanged();
    partial void OnVisiting_PlaceChanging(string value);
    partial void OnVisiting_PlaceChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnBank_AccountChanging(string value);
    partial void OnBank_AccountChanged();
    partial void OnHabitsChanging(string value);
    partial void OnHabitsChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnPolice_StationChanging(string value);
    partial void OnPolice_StationChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPAddress1Changing(string value);
    partial void OnPAddress1Changed();
    partial void OnPAddress2Changing(string value);
    partial void OnPAddress2Changed();
    partial void OnPAddress3Changing(string value);
    partial void OnPAddress3Changed();
    partial void OnPPolice_StationChanging(string value);
    partial void OnPPolice_StationChanged();
    partial void OnPStateChanging(string value);
    partial void OnPStateChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnBuiltChanging(string value);
    partial void OnBuiltChanged();
    partial void OnHeightChanging(string value);
    partial void OnHeightChanged();
    partial void OnWeightChanging(string value);
    partial void OnWeightChanged();
    partial void OnSkin_ColorChanging(string value);
    partial void OnSkin_ColorChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnLogitudeChanging(string value);
    partial void OnLogitudeChanged();
    partial void OnLatitudeChanging(string value);
    partial void OnLatitudeChanged();
    partial void OnPicture_FrontChanging(string value);
    partial void OnPicture_FrontChanged();
    partial void OnPicture_Side_LeftChanging(string value);
    partial void OnPicture_Side_LeftChanged();
    partial void OnPicture_Side_RightChanging(string value);
    partial void OnPicture_Side_RightChanged();
    partial void OnPicture_UinqChanging(string value);
    partial void OnPicture_UinqChanged();
    partial void OnOther_RemarksChanging(string value);
    partial void OnOther_RemarksChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnClassificationChanging(string value);
    partial void OnClassificationChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnGangNameChanging(string value);
    partial void OnGangNameChanged();
    partial void OnAdvocateChanging(string value);
    partial void OnAdvocateChanged();
    partial void OnBailerChanging(string value);
    partial void OnBailerChanged();
    partial void OnRemarksAdvChanging(string value);
    partial void OnRemarksAdvChanged();
    #endregion
		
		public Tbl_Criminal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Short_Name", DbType="VarChar(50)")]
		public string Short_Name
		{
			get
			{
				return this._Short_Name;
			}
			set
			{
				if ((this._Short_Name != value))
				{
					this.OnShort_NameChanging(value);
					this.SendPropertyChanging();
					this._Short_Name = value;
					this.SendPropertyChanged("Short_Name");
					this.OnShort_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accused_FName", DbType="VarChar(50)")]
		public string Accused_FName
		{
			get
			{
				return this._Accused_FName;
			}
			set
			{
				if ((this._Accused_FName != value))
				{
					this.OnAccused_FNameChanging(value);
					this.SendPropertyChanging();
					this._Accused_FName = value;
					this.SendPropertyChanged("Accused_FName");
					this.OnAccused_FNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cast", DbType="VarChar(50)")]
		public string Cast
		{
			get
			{
				return this._Cast;
			}
			set
			{
				if ((this._Cast != value))
				{
					this.OnCastChanging(value);
					this.SendPropertyChanging();
					this._Cast = value;
					this.SendPropertyChanged("Cast");
					this.OnCastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearofBirth", DbType="VarChar(10)")]
		public string YearofBirth
		{
			get
			{
				return this._YearofBirth;
			}
			set
			{
				if ((this._YearofBirth != value))
				{
					this.OnYearofBirthChanging(value);
					this.SendPropertyChanging();
					this._YearofBirth = value;
					this.SendPropertyChanged("YearofBirth");
					this.OnYearofBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visiting_Place", DbType="VarChar(50)")]
		public string Visiting_Place
		{
			get
			{
				return this._Visiting_Place;
			}
			set
			{
				if ((this._Visiting_Place != value))
				{
					this.OnVisiting_PlaceChanging(value);
					this.SendPropertyChanging();
					this._Visiting_Place = value;
					this.SendPropertyChanged("Visiting_Place");
					this.OnVisiting_PlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="VarChar(50)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_Account", DbType="VarChar(50)")]
		public string Bank_Account
		{
			get
			{
				return this._Bank_Account;
			}
			set
			{
				if ((this._Bank_Account != value))
				{
					this.OnBank_AccountChanging(value);
					this.SendPropertyChanging();
					this._Bank_Account = value;
					this.SendPropertyChanged("Bank_Account");
					this.OnBank_AccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habits", DbType="VarChar(50)")]
		public string Habits
		{
			get
			{
				return this._Habits;
			}
			set
			{
				if ((this._Habits != value))
				{
					this.OnHabitsChanging(value);
					this.SendPropertyChanging();
					this._Habits = value;
					this.SendPropertyChanged("Habits");
					this.OnHabitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(50)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Police_Station", DbType="VarChar(50)")]
		public string Police_Station
		{
			get
			{
				return this._Police_Station;
			}
			set
			{
				if ((this._Police_Station != value))
				{
					this.OnPolice_StationChanging(value);
					this.SendPropertyChanging();
					this._Police_Station = value;
					this.SendPropertyChanged("Police_Station");
					this.OnPolice_StationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAddress1", DbType="VarChar(50)")]
		public string PAddress1
		{
			get
			{
				return this._PAddress1;
			}
			set
			{
				if ((this._PAddress1 != value))
				{
					this.OnPAddress1Changing(value);
					this.SendPropertyChanging();
					this._PAddress1 = value;
					this.SendPropertyChanged("PAddress1");
					this.OnPAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAddress2", DbType="VarChar(50)")]
		public string PAddress2
		{
			get
			{
				return this._PAddress2;
			}
			set
			{
				if ((this._PAddress2 != value))
				{
					this.OnPAddress2Changing(value);
					this.SendPropertyChanging();
					this._PAddress2 = value;
					this.SendPropertyChanged("PAddress2");
					this.OnPAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAddress3", DbType="VarChar(50)")]
		public string PAddress3
		{
			get
			{
				return this._PAddress3;
			}
			set
			{
				if ((this._PAddress3 != value))
				{
					this.OnPAddress3Changing(value);
					this.SendPropertyChanging();
					this._PAddress3 = value;
					this.SendPropertyChanged("PAddress3");
					this.OnPAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPolice_Station", DbType="VarChar(50)")]
		public string PPolice_Station
		{
			get
			{
				return this._PPolice_Station;
			}
			set
			{
				if ((this._PPolice_Station != value))
				{
					this.OnPPolice_StationChanging(value);
					this.SendPropertyChanging();
					this._PPolice_Station = value;
					this.SendPropertyChanged("PPolice_Station");
					this.OnPPolice_StationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PState", DbType="VarChar(50)")]
		public string PState
		{
			get
			{
				return this._PState;
			}
			set
			{
				if ((this._PState != value))
				{
					this.OnPStateChanging(value);
					this.SendPropertyChanging();
					this._PState = value;
					this.SendPropertyChanged("PState");
					this.OnPStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(13)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Built", DbType="VarChar(50)")]
		public string Built
		{
			get
			{
				return this._Built;
			}
			set
			{
				if ((this._Built != value))
				{
					this.OnBuiltChanging(value);
					this.SendPropertyChanging();
					this._Built = value;
					this.SendPropertyChanged("Built");
					this.OnBuiltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="VarChar(50)")]
		public string Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="VarChar(50)")]
		public string Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skin_Color", DbType="VarChar(50)")]
		public string Skin_Color
		{
			get
			{
				return this._Skin_Color;
			}
			set
			{
				if ((this._Skin_Color != value))
				{
					this.OnSkin_ColorChanging(value);
					this.SendPropertyChanging();
					this._Skin_Color = value;
					this.SendPropertyChanged("Skin_Color");
					this.OnSkin_ColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logitude", DbType="VarChar(50)")]
		public string Logitude
		{
			get
			{
				return this._Logitude;
			}
			set
			{
				if ((this._Logitude != value))
				{
					this.OnLogitudeChanging(value);
					this.SendPropertyChanging();
					this._Logitude = value;
					this.SendPropertyChanged("Logitude");
					this.OnLogitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="VarChar(50)")]
		public string Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Front", DbType="VarChar(MAX)")]
		public string Picture_Front
		{
			get
			{
				return this._Picture_Front;
			}
			set
			{
				if ((this._Picture_Front != value))
				{
					this.OnPicture_FrontChanging(value);
					this.SendPropertyChanging();
					this._Picture_Front = value;
					this.SendPropertyChanged("Picture_Front");
					this.OnPicture_FrontChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Side_Left", DbType="NVarChar(MAX)")]
		public string Picture_Side_Left
		{
			get
			{
				return this._Picture_Side_Left;
			}
			set
			{
				if ((this._Picture_Side_Left != value))
				{
					this.OnPicture_Side_LeftChanging(value);
					this.SendPropertyChanging();
					this._Picture_Side_Left = value;
					this.SendPropertyChanged("Picture_Side_Left");
					this.OnPicture_Side_LeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Side_Right", DbType="VarChar(MAX)")]
		public string Picture_Side_Right
		{
			get
			{
				return this._Picture_Side_Right;
			}
			set
			{
				if ((this._Picture_Side_Right != value))
				{
					this.OnPicture_Side_RightChanging(value);
					this.SendPropertyChanging();
					this._Picture_Side_Right = value;
					this.SendPropertyChanged("Picture_Side_Right");
					this.OnPicture_Side_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Uinq", DbType="VarChar(MAX)")]
		public string Picture_Uinq
		{
			get
			{
				return this._Picture_Uinq;
			}
			set
			{
				if ((this._Picture_Uinq != value))
				{
					this.OnPicture_UinqChanging(value);
					this.SendPropertyChanging();
					this._Picture_Uinq = value;
					this.SendPropertyChanged("Picture_Uinq");
					this.OnPicture_UinqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_Remarks", DbType="VarChar(MAX)")]
		public string Other_Remarks
		{
			get
			{
				return this._Other_Remarks;
			}
			set
			{
				if ((this._Other_Remarks != value))
				{
					this.OnOther_RemarksChanging(value);
					this.SendPropertyChanging();
					this._Other_Remarks = value;
					this.SendPropertyChanged("Other_Remarks");
					this.OnOther_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="VarChar(50)")]
		public string Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(100)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GangName", DbType="VarChar(100)")]
		public string GangName
		{
			get
			{
				return this._GangName;
			}
			set
			{
				if ((this._GangName != value))
				{
					this.OnGangNameChanging(value);
					this.SendPropertyChanging();
					this._GangName = value;
					this.SendPropertyChanged("GangName");
					this.OnGangNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advocate", DbType="VarChar(100)")]
		public string Advocate
		{
			get
			{
				return this._Advocate;
			}
			set
			{
				if ((this._Advocate != value))
				{
					this.OnAdvocateChanging(value);
					this.SendPropertyChanging();
					this._Advocate = value;
					this.SendPropertyChanged("Advocate");
					this.OnAdvocateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bailer", DbType="VarChar(100)")]
		public string Bailer
		{
			get
			{
				return this._Bailer;
			}
			set
			{
				if ((this._Bailer != value))
				{
					this.OnBailerChanging(value);
					this.SendPropertyChanging();
					this._Bailer = value;
					this.SendPropertyChanged("Bailer");
					this.OnBailerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarksAdv", DbType="VarChar(MAX)")]
		public string RemarksAdv
		{
			get
			{
				return this._RemarksAdv;
			}
			set
			{
				if ((this._RemarksAdv != value))
				{
					this.OnRemarksAdvChanging(value);
					this.SendPropertyChanging();
					this._RemarksAdv = value;
					this.SendPropertyChanged("RemarksAdv");
					this.OnRemarksAdvChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Modus")]
	public partial class Tbl_Modus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Modus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnModusChanging(string value);
    partial void OnModusChanged();
    #endregion
		
		public Tbl_Modus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modus", DbType="VarChar(50)")]
		public string Modus
		{
			get
			{
				return this._Modus;
			}
			set
			{
				if ((this._Modus != value))
				{
					this.OnModusChanging(value);
					this.SendPropertyChanging();
					this._Modus = value;
					this.SendPropertyChanged("Modus");
					this.OnModusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
